PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',active INTEGER NOT NULL DEFAULT 1,last_login TEXT,must_change_password INTEGER NOT NULL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payment_types(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,category TEXT,notes TEXT,active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS exams(id INTEGER PRIMARY KEY AUTOINCREMENT,unit TEXT NOT NULL,name TEXT NOT NULL,base_price REAL DEFAULT 0,active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(unit,name));
CREATE TABLE IF NOT EXISTS price_plans(id INTEGER PRIMARY KEY AUTOINCREMENT,payment_type_id INTEGER NOT NULL,name TEXT NOT NULL,version INTEGER DEFAULT 1,valid_from TEXT NOT NULL,valid_to TEXT,active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(payment_type_id) REFERENCES payment_types(id));
CREATE TABLE IF NOT EXISTS price_plan_items(id INTEGER PRIMARY KEY AUTOINCREMENT,price_plan_id INTEGER NOT NULL,exam_id INTEGER NOT NULL,price REAL NOT NULL,coverage_percentage REAL DEFAULT 0,active INTEGER DEFAULT 1,UNIQUE(price_plan_id,exam_id),FOREIGN KEY(price_plan_id) REFERENCES price_plans(id),FOREIGN KEY(exam_id) REFERENCES exams(id));
CREATE TABLE IF NOT EXISTS patients(id INTEGER PRIMARY KEY AUTOINCREMENT,legacy_id INTEGER,name TEXT NOT NULL,payment_type TEXT,phone TEXT,exam TEXT,exam_price REAL DEFAULT 0,coverage_percentage REAL DEFAULT 0,coverage_amount REAL DEFAULT 0,additional_fees REAL DEFAULT 0,discount REAL DEFAULT 0,total_amount REAL DEFAULT 0,paid_amount REAL DEFAULT 0,remaining_amount REAL DEFAULT 0,payment_method TEXT DEFAULT 'Cash',doctor TEXT,notes TEXT,username TEXT,unit TEXT,case_date TEXT,timestamp TEXT,price_plan_id INTEGER,price_plan_item_id INTEGER,price_snapshot TEXT,row_version INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS appointments(id INTEGER PRIMARY KEY AUTOINCREMENT,patient_name TEXT NOT NULL,phone TEXT NOT NULL,payment_type TEXT,unit TEXT NOT NULL,exam TEXT,appointment_date TEXT NOT NULL,appointment_time TEXT,period TEXT,doctor TEXT,notes TEXT,status TEXT DEFAULT 'Booked',created_by TEXT,updated_by TEXT,converted_patient_id INTEGER,row_version INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT,action TEXT,entity_type TEXT,entity_id INTEGER,old_data TEXT,new_data TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);
CREATE INDEX IF NOT EXISTS idx_patients_date ON patients(case_date);
CREATE INDEX IF NOT EXISTS idx_patients_phone ON patients(phone);
CREATE INDEX IF NOT EXISTS idx_appt_date ON appointments(appointment_date);

CREATE TABLE IF NOT EXISTS role_permissions(role TEXT NOT NULL,permission TEXT NOT NULL,allowed INTEGER NOT NULL DEFAULT 1,PRIMARY KEY(role,permission));
